name: CI Frontend MenuQr

on:
  push:
    branches: ['**']
  pull_request:
    branches: ['**']

jobs:
  frontend-build:
    name: Compilation frontend (Angular)
    runs-on: ubuntu-latest

    steps:
      - name: Récupère le code
        uses: actions/checkout@v4

      - name: Installe Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Installe les dépendances
        run: npm ci

      - name: Compile en mode production
        run: npm run build -- --configuration=production